module ChatDDS {

    struct Time {
        unsigned short hour;
        unsigned short min;
        unsigned short sec;
    };

    struct Message {
        string username;
        Time time;
        string content;
    };
    #pragma keylist Message username

    enum SystemMessageType { JOIN, QUIT };

    struct SystemMessage {
        string username;
        SystemMessageType type;
    };
    #pragma keylist SystemMessage username
};
