module ChatDDS {

    struct Time {
        unsigned short hour;
        unsigned short min;
        unsigned short sec;
    };

    struct Message {
        unsigned short id;
        string username;
        Time time;
        string content;
    };
    #pragma keylist Message id, username

    enum SystemMessageType {
        JOIN,
        QUIT
    };

    struct SystemMessage {
        string username;
        SystemMessageType type;
    };
    #pragma keylist SystemMessage
};
